import {
  createHash,
  randomBytes,
  randomUUID,
  timingSafeEqual,
} from 'node:crypto';
import { load } from 'cheerio';
import { downloadArticleUrl } from './article-download';
import { verifiedDownloadBody } from './article-verified-download';
import { decodeInlineImage } from './collection/image-fetch';
import { validateImageSignature } from './collection/browser-dom-adapter';
import {
  parseWereadDirectory,
  verifyWereadArticleBody,
} from './collection/weread-directory';
import {
  assertProviderPage,
  ProviderArticle,
} from './collection/subscription-provider';
import { canonicalArticleUrl } from './collection/collection-format';
import { privateOnlineMode } from './private-access';

export type BrowserBinding = {
  tabId: number;
  windowId: number;
  pageUrl: string;
};
export type BrowserTaskTarget = { url: string; mpId?: string; name?: string };
export type BrowserObservation = {
  pageUrl: string;
  html: string;
  images: Array<{ index: number; inline: string }>;
  projection: { bookId: string; current: unknown; bodyFingerprint: string };
};
export class BrowserTaskError extends Error {
  constructor(
    readonly code: string,
    readonly status = 422,
  ) {
    super(code);
  }
}
function fail(code: string, status = 422): never {
  throw new BrowserTaskError(code, status);
}
const sha = (raw: string) => createHash('sha256').update(raw).digest('hex');
export const BROWSER_TASK_TTL = 5 * 60 * 1000;
export const BROWSER_TASK_MAX_BYTES = 35_000_000;
const exact = (value: unknown, keys: string[]) =>
  !!value &&
  typeof value === 'object' &&
  !Array.isArray(value) &&
  Object.keys(value).length === keys.length &&
  keys.every((key) => Object.prototype.hasOwnProperty.call(value, key));

export function browserBodyFingerprint(html: string) {
  const $ = load(html);
  const body = $('#js_content');
  return sha(
    JSON.stringify({
      text: body.text().normalize('NFKC').replace(/\s+/gu, ''),
      images: body.find('img').length,
    }),
  );
}

/** Candidate official display schema; route approval is a separate gate.
 * Fresh articles need no previous DB/cache record or body hash. They must bind
 * the requested original link to the current official chapter and raw-body
 * projection. Page assertions alone are never a server authority or CAPTCHA proof.
 */
export function verifyBrowserTaskObservation(
  target: BrowserTaskTarget,
  raw: unknown,
): ProviderArticle {
  if (!exact(raw, ['pageUrl', 'html', 'images', 'projection']))
    fail('OBSERVATION_SCHEMA');
  const observation = raw as BrowserObservation;
  if (
    typeof observation.html !== 'string' ||
    Buffer.byteLength(observation.html) > 5_000_000 ||
    !Array.isArray(observation.images) ||
    observation.images.length > 60 ||
    !exact(observation.projection, ['bookId', 'current', 'bodyFingerprint'])
  )
    fail('OBSERVATION_SIZE');
  const { bookId, current, bodyFingerprint } = observation.projection;
  if (
    typeof bodyFingerprint !== 'string' ||
    !/^[a-f0-9]{64}$/.test(bodyFingerprint)
  )
    fail('BODY_PROJECTION');
  // Reuse the actual official directory contract; never trust title-only links.
  const projected = current as any;
  if (
    !exact(projected, ['reviewId', 'review']) ||
    !exact(projected.review, [
      'reviewId',
      'belongBookId',
      'bookId',
      'type',
      'mpInfo',
    ]) ||
    !exact(projected.review.mpInfo, [
      'originalId',
      'title',
      'mp_name',
      'time',
      'pic_url',
    ])
  )
    fail('PROJECTION_SCHEMA');
  const name = target.name || projected?.review?.mpInfo?.mp_name;
  if (typeof name !== 'string' || name.length > 1000) fail('PUBLISHER_INVALID');
  const candidate = parseWereadDirectory(
    { reviews: [{ subReviews: [current] }] },
    { mpId: target.mpId || bookId, name },
  ).articles[0];
  if (!candidate || candidate.mpId !== bookId) fail('TARGET_MISMATCH');
  const requested = downloadArticleUrl(target.url);
  const original = `https://mp.weixin.qq.com/s/${candidate.originalId.replace(/~/g, '_')}`;
  const requestedIsShort = new URL(requested).pathname !== '/s';
  if (requestedIsShort && requested !== original) fail('TARGET_MISMATCH');
  const $ = load(observation.html);
  if (
    $('#js_content').length !== 1 ||
    $('script').length !== 1 ||
    $('iframe,form,input,object,embed,video,audio,svg,base,link,style').length
  )
    fail('BODY_STRUCTURE');
  // This compact metadata script is generated by the extension's strict scalar
  // allowlist; no arbitrary page JS is evaluated or accepted by the adapter.
  const metadata = $('script').html() || '';
  if (
    !/^(?:var (?:biz|mid|idx|sn|ct|create_time)="[A-Za-z0-9+/=]+";)+$/.test(
      metadata,
    )
  )
    fail('METADATA_SCHEMA');
  const body = $('#js_content');
  const images = body.find('img').toArray();
  if (
    images.length !== observation.images.length ||
    browserBodyFingerprint(observation.html) !== bodyFingerprint
  )
    fail('BODY_INCOMPLETE');
  let total = 0;
  for (let index = 0; index < images.length; index++) {
    const entry = observation.images[index];
    if (
      !exact(entry, ['index', 'inline']) ||
      entry.index !== index ||
      typeof entry.inline !== 'string' ||
      $(images[index]).attr('src') !== `wewe-image:${index}`
    )
      fail('IMAGE_BINDING');
    const image = decodeInlineImage(entry.inline);
    total += image.bytes.length;
    if (total > 20_000_000 || !validateImageSignature(image.bytes, image.type))
      fail('IMAGE_BYTES');
    $(images[index]).removeAttr('data-src').attr('src', entry.inline);
  }
  // Existing parser checks static biz/mid/idx, independently present original
  // creation time, canonical, publisher and title. No directory time substitution.
  const article = verifyWereadArticleBody(candidate, $.html());
  if (!requestedIsShort && canonicalArticleUrl(requested).url !== article.url)
    fail('TARGET_MISMATCH');
  article.contentHtml = verifiedDownloadBody(article.contentHtml);
  assertProviderPage(
    {
      articles: [article],
      coverage: 'recent-window',
      upstreamCount: 1,
      bodyMissing: 0,
      imageBlocked: 0,
    },
    candidate.mpId,
  );
  return article;
}

type Pending = {
  target: BrowserTaskTarget;
  expires: number;
  binding?: BrowserBinding;
  nonce?: string;
  resolve: (article: ProviderArticle) => void;
  reject: (error: Error) => void;
  timer: ReturnType<typeof setTimeout>;
};
export type BrowserTaskConfiguration = {
  /** No environment auto-enable. Install, pairing and route acceptance are separate user decisions. */
  enabled?: boolean;
  routeVerified?: boolean;
  pairingKey?: string;
  extensionOrigin?: string;
  localOrigin?: string;
};

/** In-memory, one-shot tasks; restart revokes every task/nonce. No production
 * database, global subscription state or remote image/network fetcher here.
 * Task creation is an internal function; there is no browser body-upload/issue API.
 */
export class BrowserTaskBroker {
  private tasks = new Map<string, Pending>();
  private readonly config: BrowserTaskConfiguration;
  constructor(config: BrowserTaskConfiguration = {}) {
    this.config = Object.freeze({ ...config });
  }
  private available() {
    if (privateOnlineMode()) fail('LOCAL_ONLY', 403);
    if (!this.config.enabled) fail('BROWSER_TASK_DISABLED', 409);
    if (!this.config.routeVerified) fail('LIVE_ROUTE_UNVERIFIED', 409);
    if (
      !/^[A-Za-z0-9_-]{43}$/.test(this.config.pairingKey || '') ||
      !/^chrome-extension:\/\/[a-p]{32}$/.test(
        this.config.extensionOrigin || '',
      ) ||
      !/^http:\/\/127\.0\.0\.1:\d{1,5}$/.test(this.config.localOrigin || '')
    )
      fail('PAIRING_NOT_CONFIGURED', 409);
  }
  preflight(req: {
    socket: { remoteAddress?: string };
    headers: Record<string, unknown>;
  }) {
    this.available();
    const origin = this.config.extensionOrigin!;
    const host = new URL(this.config.localOrigin!).host;
    if (
      !['127.0.0.1', '::1', '::ffff:127.0.0.1'].includes(
        req.socket.remoteAddress || '',
      ) ||
      req.headers.host !== host ||
      req.headers.origin !== origin
    )
      fail('LOCAL_ORIGIN', 403);
    return origin;
  }
  authorize(req: {
    socket: { remoteAddress?: string };
    headers: Record<string, unknown>;
  }) {
    const origin = this.preflight(req);
    const key = req.headers['x-wewe-pairing'];
    if (
      typeof key !== 'string' ||
      Buffer.byteLength(key) !== 43 ||
      !timingSafeEqual(Buffer.from(key), Buffer.from(this.config.pairingKey!))
    )
      fail('PAIRING_REQUIRED', 401);
    if (req.headers['content-type'] !== 'application/json')
      fail('CONTENT_TYPE', 415);
    return origin;
  }
  /** Called after the original WeWe action's existing auth/Origin checks.
   * Use result only with original request/res in saveVerifiedArticle, or with
   * the existing refresh transaction after all selected article tasks succeed.
   */
  issue(target: BrowserTaskTarget) {
    this.available();
    if (
      !target ||
      Object.keys(target).some((k) => !['url', 'mpId', 'name'].includes(k))
    )
      fail('TARGET_INVALID');
    const url = downloadArticleUrl(target.url);
    if (target.mpId !== undefined && !/^MP_WXS_\d{5,15}$/.test(target.mpId))
      fail('TARGET_INVALID');
    if (
      target.name !== undefined &&
      (typeof target.name !== 'string' ||
        !target.name.trim() ||
        target.name.length > 1000)
    )
      fail('TARGET_INVALID');
    if (this.tasks.size >= 4) fail('TASK_CAPACITY', 409);
    const taskId = randomUUID();
    const expires = Date.now() + BROWSER_TASK_TTL;
    let resolve!: (article: ProviderArticle) => void;
    let reject!: (error: Error) => void;
    const result = new Promise<ProviderArticle>((yes, no) => {
      resolve = yes;
      reject = no;
    });
    // Keep an abandoned HTTP owner from producing an unhandled rejection.
    void result.catch(() => {});
    const timer = setTimeout(() => this.cancel(taskId), BROWSER_TASK_TTL);
    timer.unref?.();
    this.tasks.set(taskId, {
      target: { ...target, url },
      expires,
      resolve,
      reject,
      timer,
    });
    return { taskId, expiresAt: new Date(expires).toISOString(), result };
  }
  private pending(taskId: unknown) {
    if (typeof taskId !== 'string' || !/^[a-f0-9-]{36}$/.test(taskId))
      fail('TASK_INVALID', 400);
    const task = this.tasks.get(taskId);
    if (!task) fail('TASK_GONE', 410);
    if (Date.now() >= task.expires) {
      this.cancel(taskId);
      fail('TASK_EXPIRED', 410);
    }
    return task;
  }
  private binding(raw: unknown): BrowserBinding {
    if (!exact(raw, ['tabId', 'windowId', 'pageUrl'])) fail('SOURCE_BINDING');
    const value = raw as BrowserBinding;
    if (
      !Number.isSafeInteger(value.tabId) ||
      value.tabId < 0 ||
      !Number.isSafeInteger(value.windowId) ||
      value.windowId < 0 ||
      typeof value.pageUrl !== 'string' ||
      !/^https:\/\/weread\.qq\.com\/web\/mp\/reader\/[A-Za-z0-9_-]{1,256}$/.test(
        value.pageUrl,
      )
    )
      fail('SOURCE_BINDING');
    return { ...value };
  }
  claim(taskId: unknown, binding: unknown) {
    const task = this.pending(taskId);
    if (task.binding) fail('TASK_ALREADY_CLAIMED', 409);
    task.binding = this.binding(binding);
    task.nonce = randomBytes(32).toString('base64url');
    return {
      nonce: task.nonce,
      expiresAt: new Date(task.expires).toISOString(),
    };
  }
  complete(
    taskId: unknown,
    nonce: unknown,
    binding: unknown,
    observation: unknown,
  ) {
    const task = this.pending(taskId);
    if (
      !task.binding ||
      nonce !== task.nonce ||
      JSON.stringify(this.binding(binding)) !== JSON.stringify(task.binding)
    )
      fail('TASK_BINDING', 403);
    // Consume before parsing/publication, including failure. No cross-task reuse.
    this.tasks.delete(taskId as string);
    clearTimeout(task.timer);
    try {
      if (
        Buffer.byteLength(JSON.stringify(observation) || '') >
        BROWSER_TASK_MAX_BYTES
      )
        fail('PAYLOAD_SIZE', 413);
      if ((observation as BrowserObservation)?.pageUrl !== task.binding.pageUrl)
        fail('SOURCE_BINDING');
      const article = verifyBrowserTaskObservation(task.target, observation);
      task.resolve(article);
      return { accepted: true };
    } catch (error) {
      task.reject(new BrowserTaskError('OBSERVATION_REJECTED'));
      throw error;
    }
  }
  cancel(taskId: unknown, nonce?: unknown, binding?: unknown) {
    const task = this.tasks.get(String(taskId));
    if (!task) return;
    if (
      nonce !== undefined &&
      (nonce !== task.nonce ||
        JSON.stringify(this.binding(binding)) !== JSON.stringify(task.binding))
    )
      fail('TASK_BINDING', 403);
    clearTimeout(task.timer);
    this.tasks.delete(String(taskId));
    task.reject(new BrowserTaskError('TASK_CANCELLED', 410));
  }
  close() {
    for (const key of this.tasks.keys()) this.cancel(key);
  }
}
